In [1]:
import numpy as np

In [2]:
a=np.arange(9).reshape(3,3)

In [3]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [4]:
for row in a:
    print(row)

[0 1 2]
[3 4 5]
[6 7 8]


In [5]:
for row in a:
    print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [6]:
for row in a:
    print (row)

[0 1 2]
[3 4 5]
[6 7 8]


In [7]:
for row in a:
    for cell in row:
        print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [8]:
for row in a:
    for cell in row:
        print(cell)

0
1
2
3
4
5
6
7
8


In [12]:
for row in a.flatten():
    print (row)


[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [14]:
for row in a.flatten():
    print (row)


0
1
2
3
4
5
6
7
8


In [16]:
for x in np.nditer(a,order='C'):
    print(x)

0
1
2
3
4
5
6
7
8


In [17]:
for x in np.nditer(a,order='F'):
    print(x)


0
3
6
1
4
7
2
5
8


In [19]:
for x in np.nditer(a,order='F',flags=['external_loop']):
    print (x)


[0 3 6]
[1 4 7]
[2 5 8]


In [21]:
for x in np.nditer(a,order='F',op_flags=['readwrite']):
    x[...]=x*x
    print(x)

0
9
36
1
16
49
4
25
64


In [22]:
a

array([[ 0,  1,  4],
       [ 9, 16, 25],
       [36, 49, 64]])

In [23]:
b=np.arange(0,1).reshape(1,1)

In [24]:
b

array([[0]])

In [26]:
for x,y in np.nditer([a,b]):
    print(x,y)

0 0
1 0
4 0
9 0
16 0
25 0
36 0
49 0
64 0


In [27]:
import pandas pd

SyntaxError: invalid syntax (3546497058.py, line 1)

In [28]:
import pandas as pd

In [29]:
import csv

In [30]:
with open("D:\\personal\\Data Science\\movies.csv") as f:
    data= list(csv.reader(f))
    print(data)

[['title', 'industry', 'release_year', 'imdb_rating', 'studio', 'budget', 'revenue', 'unit', 'currency', 'language'], ['Pather Panchali', 'Bollywood', '1955', '8.3', 'Government of West Bengal', '70000', '100000', 'Thousands', 'INR', 'Bengali'], ['Doctor Strange in the Multiverse of Madness', 'Hollywood', '2022', '7', 'Marvel Studios', '200', '954.8', 'Millions', 'USD', 'English'], ['Thor: The Dark World ', 'Hollywood', '2013', '6.8', 'Marvel Studios', '165', '644.8', 'Millions', 'USD', 'English'], ['Thor: Ragnarok ', 'Hollywood', '2017', '7.9', 'Marvel Studios', '180', '854', 'Millions', 'USD', 'English'], ['Thor: Love and Thunder ', 'Hollywood', '2022', '6.8', 'Marvel Studios', '250', '670', 'Millions', 'USD', 'English'], ['The Shawshank Redemption', 'Hollywood', '1994', '9.3', 'Castle Rock Entertainment', '25', '73.3', 'Millions', 'USD', 'English'], ['Interstellar', 'Hollywood', '2014', '8.6', 'Warner Bros. Pictures', '165', '701.8', 'Millions', 'USD', 'English'], ['The Pursuit of H

In [31]:
import pandas as pd

In [34]:
df=pd.read_csv("D:\\personal\\Data Science\\movies.csv") 
df



title   industry  release_year  \
0                               Pather Panchali  Bollywood          1955   
1   Doctor Strange in the Multiverse of Madness  Hollywood          2022   
2                         Thor: The Dark World   Hollywood          2013   
3                               Thor: Ragnarok   Hollywood          2017   
4                       Thor: Love and Thunder   Hollywood          2022   
5                      The Shawshank Redemption  Hollywood          1994   
6                                  Interstellar  Hollywood          2014   
7                      The Pursuit of Happyness  Hollywood          2006   
8                                     Gladiator  Hollywood          2000   
9                                       Titanic  Hollywood          1997   
10                        It's a Wonderful Life  Hollywood          1946   
11                                       Avatar  Hollywood          2009   
12                                The Godfather  Hollywood          1972   
13                              The Dark Knight  Hollywood          2008   
14                             Schindler's List  Hollywood          1993   
15                                Jurassic Park  Hollywood          1993   
16                                     Parasite  Hollywood          2019   
17                            Avengers: Endgame  Hollywood          2019   
18                       Avengers: Infinity War  Hollywood          2018   
19           Captain America: The First Avenger  Hollywood          2011   
20          Captain America: The Winter Soldier  Hollywood          2014   
21                  Dilwale Dulhania Le Jayenge  Bollywood          1995   
22                                     3 Idiots  Bollywood          2009   
23                     Kabhi Khushi Kabhie Gham  Bollywood          2001   
24                             Bajirao Mastani   Bollywood          2015   
25                             Taare Zameen Par  Bollywood          2007   
26                          Munna Bhai M.B.B.S.  Bollywood          2003   
27                                           PK  Bollywood          2014   
28                                        Sanju  Bollywood          2018   
29                            The Kashmir Files  Bollywood          2022   
30                            Bajrangi Bhaijaan  Bollywood          2015   
31                                       Race 3  Bollywood          2018   
32                                    Shershaah  Bollywood          2021   
33                             K.G.F: Chapter 2  Bollywood          2022   
34                    Pushpa: The Rise - Part 1  Bollywood          2021   
35                                          RRR  Bollywood          2022   
36                     Baahubali: The Beginning  Bollywood          2015   

    imdb_rating                     studio    budget   revenue       unit  \
0           8.3  Government of West Bengal  70000.00  100000.0  Thousands   
1           7.0             Marvel Studios    200.00     954.8   Millions   
2           6.8             Marvel Studios    165.00     644.8   Millions   
3           7.9             Marvel Studios    180.00     854.0   Millions   
4           6.8             Marvel Studios    250.00     670.0   Millions   
5           9.3  Castle Rock Entertainment     25.00      73.3   Millions   
6           8.6      Warner Bros. Pictures    165.00     701.8   Millions   
7           8.0          Columbia Pictures     55.00     307.1   Millions   
8           8.5       Universal Pictures      103.00     460.5   Millions   
9           7.9         Paramount Pictures    200.00    2202.0   Millions   
10          8.6              Liberty Films      3.18       3.3   Millions   
11          7.8           20th Century Fox    237.00    2847.0   Millions   
12          9.2         Paramount Pictures      7.20     291.0   Millions   
13          9.0                    Syncopy    185.00    1006.0   Millions  

In [35]:
df.head()

title   industry  release_year  \
0                              Pather Panchali  Bollywood          1955   
1  Doctor Strange in the Multiverse of Madness  Hollywood          2022   
2                        Thor: The Dark World   Hollywood          2013   
3                              Thor: Ragnarok   Hollywood          2017   
4                      Thor: Love and Thunder   Hollywood          2022   

   imdb_rating                     studio   budget   revenue       unit  \
0          8.3  Government of West Bengal  70000.0  100000.0  Thousands   
1          7.0             Marvel Studios    200.0     954.8   Millions   
2          6.8             Marvel Studios    165.0     644.8   Millions   
3          7.9             Marvel Studios    180.0     854.0   Millions   
4          6.8             Marvel Studios    250.0     670.0   Millions   

  currency language  
0      INR  Bengali  
1      USD  English  
2      USD  English  
3      USD  English  
4      USD  English

In [36]:
df.tail()

title   industry  release_year  imdb_rating  \
32                  Shershaah  Bollywood          2021          8.4   
33           K.G.F: Chapter 2  Bollywood          2022          8.4   
34  Pushpa: The Rise - Part 1  Bollywood          2021          7.6   
35                        RRR  Bollywood          2022          8.0   
36   Baahubali: The Beginning  Bollywood          2015          8.0   

                 studio  budget  revenue      unit currency language  
32   Dharma Productions   500.0    950.0  Millions      INR    Hindi  
33        Hombale Films     1.0     12.5  Billions      INR  Kannada  
34  Mythri Movie Makers     2.0      3.6  Billions      INR   Telugu  
35    DVV Entertainment     5.5     12.0  Billions      INR   Telugu  
36     Arka Media Works     1.8      6.5  Billions      INR   Telugu

In [37]:
df.tail(4)

title   industry  release_year  imdb_rating  \
33           K.G.F: Chapter 2  Bollywood          2022          8.4   
34  Pushpa: The Rise - Part 1  Bollywood          2021          7.6   
35                        RRR  Bollywood          2022          8.0   
36   Baahubali: The Beginning  Bollywood          2015          8.0   

                 studio  budget  revenue      unit currency language  
33        Hombale Films     1.0     12.5  Billions      INR  Kannada  
34  Mythri Movie Makers     2.0      3.6  Billions      INR   Telugu  
35    DVV Entertainment     5.5     12.0  Billions      INR   Telugu  
36     Arka Media Works     1.8      6.5  Billions      INR   Telugu

In [38]:
DF[5:9]

NameError: name 'DF' is not defined

In [39]:
df[5:9]

title   industry  release_year  imdb_rating  \
5  The Shawshank Redemption  Hollywood          1994          9.3   
6              Interstellar  Hollywood          2014          8.6   
7  The Pursuit of Happyness  Hollywood          2006          8.0   
8                 Gladiator  Hollywood          2000          8.5   

                      studio  budget  revenue      unit currency language  
5  Castle Rock Entertainment    25.0     73.3  Millions      USD  English  
6      Warner Bros. Pictures   165.0    701.8  Millions      USD  English  
7          Columbia Pictures    55.0    307.1  Millions      USD  English  
8       Universal Pictures     103.0    460.5  Millions      USD  English

In [40]:
df.shape()

TypeError: 'tuple' object is not callable

In [41]:
df.shape

(37, 10)

In [42]:
df["imdb_rating"]

0     8.3
1     7.0
2     6.8
3     7.9
4     6.8
5     9.3
6     8.6
7     8.0
8     8.5
9     7.9
10    8.6
11    7.8
12    9.2
13    9.0
14    9.0
15    8.2
16    8.5
17    8.4
18    8.4
19    6.9
20    7.8
21    8.0
22    8.4
23    7.4
24    7.2
25    8.3
26    8.1
27    8.1
28    NaN
29    8.3
30    8.1
31    1.9
32    8.4
33    8.4
34    7.6
35    8.0
36    8.0
Name: imdb_rating, dtype: float64

In [43]:
df.imdb_rating

0     8.3
1     7.0
2     6.8
3     7.9
4     6.8
5     9.3
6     8.6
7     8.0
8     8.5
9     7.9
10    8.6
11    7.8
12    9.2
13    9.0
14    9.0
15    8.2
16    8.5
17    8.4
18    8.4
19    6.9
20    7.8
21    8.0
22    8.4
23    7.4
24    7.2
25    8.3
26    8.1
27    8.1
28    NaN
29    8.3
30    8.1
31    1.9
32    8.4
33    8.4
34    7.6
35    8.0
36    8.0
Name: imdb_rating, dtype: float64

In [44]:
type(df.imdb_rating)

pandas.core.series.Series

In [45]:
type(df)

pandas.core.frame.DataFrame

In [46]:
dir)df)

SyntaxError: unmatched ')' (364171153.py, line 1)

In [47]:
dir(df)

['T',
 '_AXIS_LEN',
 '_AXIS_ORDERS',
 '_AXIS_TO_AXIS_NUMBER',
 '_HANDLED_TYPES',
 '__abs__',
 '__add__',
 '__and__',
 '__annotations__',
 '__array__',
 '__array_priority__',
 '__array_ufunc__',
 '__arrow_c_stream__',
 '__bool__',
 '__class__',
 '__contains__',
 '__copy__',
 '__dataframe__',
 '__dataframe_consortium_standard__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__finalize__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__imod__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__or__',
 '__pandas_priority__',
 '__pos__',
 '__pow__',
 '__r

In [48]:
dir (df.imdb_rating)

['T',
 '_AXIS_LEN',
 '_AXIS_ORDERS',
 '_AXIS_TO_AXIS_NUMBER',
 '_HANDLED_TYPES',
 '__abs__',
 '__add__',
 '__and__',
 '__annotations__',
 '__array__',
 '__array_priority__',
 '__array_ufunc__',
 '__bool__',
 '__class__',
 '__column_consortium_standard__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__finalize__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__imod__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__or__',
 '__pandas_priority__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__

In [52]:
df.imdb_rating.max(),df.imdb_rating.min(),df.imdb_rating.mean()

(np.float64(9.3), np.float64(1.9), np.float64(7.919444444444445))

In [53]:
max_rating=float(df.imdb_rating.max())
min_rating=float(df.imdb_rating.min())
mean_rating=float(df.imdb_rating.mean())

In [54]:
max_rating,min_rating,mean_rating

(9.3, 1.9, 7.919444444444445)

In [55]:
df_b=[df.industry=="Bollywood"]

In [56]:
df_b

[0      True
 1     False
 2     False
 3     False
 4     False
 5     False
 6     False
 7     False
 8     False
 9     False
 10    False
 11    False
 12    False
 13    False
 14    False
 15    False
 16    False
 17    False
 18    False
 19    False
 20    False
 21     True
 22     True
 23     True
 24     True
 25     True
 26     True
 27     True
 28     True
 29     True
 30     True
 31     True
 32     True
 33     True
 34     True
 35     True
 36     True
 Name: industry, dtype: bool]

In [58]:
df_b=df[df.industry=="Bollywood"]

In [59]:
df_b

title   industry  release_year  imdb_rating  \
0               Pather Panchali  Bollywood          1955          8.3   
21  Dilwale Dulhania Le Jayenge  Bollywood          1995          8.0   
22                     3 Idiots  Bollywood          2009          8.4   
23     Kabhi Khushi Kabhie Gham  Bollywood          2001          7.4   
24             Bajirao Mastani   Bollywood          2015          7.2   
25             Taare Zameen Par  Bollywood          2007          8.3   
26          Munna Bhai M.B.B.S.  Bollywood          2003          8.1   
27                           PK  Bollywood          2014          8.1   
28                        Sanju  Bollywood          2018          NaN   
29            The Kashmir Files  Bollywood          2022          8.3   
30            Bajrangi Bhaijaan  Bollywood          2015          8.1   
31                       Race 3  Bollywood          2018          1.9   
32                    Shershaah  Bollywood          2021          8.4   
33             K.G.F: Chapter 2  Bollywood          2022          8.4   
34    Pushpa: The Rise - Part 1  Bollywood          2021          7.6   
35                          RRR  Bollywood          2022          8.0   
36     Baahubali: The Beginning  Bollywood          2015          8.0   

                       studio   budget   revenue       unit currency language  
0   Government of West Bengal  70000.0  100000.0  Thousands      INR  Bengali  
21             Yash Raj Films    400.0    2000.0   Millions      INR    Hindi  
22         Vinod Chopra Films    550.0    4000.0   Millions      INR    Hindi  
23         Dharma Productions    390.0    1360.0   Millions      INR    Hindi  
24                        NaN      1.4       3.5   Billions      INR    Hindi  
25                        NaN    120.0    1350.0   Millions      INR    Hindi  
26   Vinod Chopra Productions    100.0     410.0   Millions      INR    Hindi  
27         Vinod Chopra Films    850.0    8540.0   Millions      INR    Hindi  
28         Vinod Chopra Films      1.0       5.9   Billions      INR    Hindi  
29                Zee Studios    250.0    3409.0   Millions      INR    Hindi  
30          Salman Khan Films    900.0   11690.0   Millions      INR    Hindi  
31          Salman Khan Films      1.8       3.1   Billions      INR    Hindi  
32         Dharma Productions    500.0     950.0   Millions      INR    Hindi  
33              Hombale Films      1.0      12.5   Billions      INR  Kannada  
34        Mythri Movie Makers      2.0       3.6   Billions      INR   Telugu  
35          DVV Entertainment      5.5      12.0   Billions      INR   Telugu  
36           Arka Media Works      1.8       6.5   Billions      INR   Telugu

In [60]:
df_h=df[df.industry=="Hollywood"]

In [61]:
df_h

title   industry  release_year  \
1   Doctor Strange in the Multiverse of Madness  Hollywood          2022   
2                         Thor: The Dark World   Hollywood          2013   
3                               Thor: Ragnarok   Hollywood          2017   
4                       Thor: Love and Thunder   Hollywood          2022   
5                      The Shawshank Redemption  Hollywood          1994   
6                                  Interstellar  Hollywood          2014   
7                      The Pursuit of Happyness  Hollywood          2006   
8                                     Gladiator  Hollywood          2000   
9                                       Titanic  Hollywood          1997   
10                        It's a Wonderful Life  Hollywood          1946   
11                                       Avatar  Hollywood          2009   
12                                The Godfather  Hollywood          1972   
13                              The Dark Knight  Hollywood          2008   
14                             Schindler's List  Hollywood          1993   
15                                Jurassic Park  Hollywood          1993   
16                                     Parasite  Hollywood          2019   
17                            Avengers: Endgame  Hollywood          2019   
18                       Avengers: Infinity War  Hollywood          2018   
19           Captain America: The First Avenger  Hollywood          2011   
20          Captain America: The Winter Soldier  Hollywood          2014   

    imdb_rating                     studio  budget  revenue      unit  \
1           7.0             Marvel Studios  200.00    954.8  Millions   
2           6.8             Marvel Studios  165.00    644.8  Millions   
3           7.9             Marvel Studios  180.00    854.0  Millions   
4           6.8             Marvel Studios  250.00    670.0  Millions   
5           9.3  Castle Rock Entertainment   25.00     73.3  Millions   
6           8.6      Warner Bros. Pictures  165.00    701.8  Millions   
7           8.0          Columbia Pictures   55.00    307.1  Millions   
8           8.5       Universal Pictures    103.00    460.5  Millions   
9           7.9         Paramount Pictures  200.00   2202.0  Millions   
10          8.6              Liberty Films    3.18      3.3  Millions   
11          7.8           20th Century Fox  237.00   2847.0  Millions   
12          9.2         Paramount Pictures    7.20    291.0  Millions   
13          9.0                    Syncopy  185.00   1006.0  Millions   
14          9.0         Universal Pictures   22.00    322.2  Millions   
15          8.2         Universal Pictures   63.00   1046.0  Millions   
16          8.5                        NaN   15.50    263.1  Millions   
17          8.4             Marvel Studios  400.00   2798.0  Millions   
18          8.4             Marvel Studios  400.00   2048.0  Millions   
19          6.9             Marvel Studios  216.70    370.6  Millions   
20          7.8             Marvel Studios  177.00    714.4  Millions   

   currency language  
1       USD  English  
2       USD  English  
3       USD  English  
4       USD  English  
5       USD  English  
6       USD  English  
7       USD  English  
8       USD  English  
9       USD  English  
10      USD  English  
11      USD  English  
12      USD  English  
13      USD  English  
14      USD  English  
15      USD  English  
16      USD  English  
17      USD  English  
18      USD  English  
19      USD  English  
20      USD  English

In [63]:
df_b.imdb_rating.min(),df_b.imdb_rating.max(),df_b.imdb_rating.mean()

(np.float64(1.9), np.float64(8.4), np.float64(7.656250000000001))

In [64]:
float(df_b.imdb_rating.min()),float(df_b.imdb_rating.max()),float(df_b.imdb_rating.mean())

(1.9, 8.4, 7.656250000000001)

In [65]:
float(df_h.imdb_rating.min()),float(df_h.imdb_rating.max()),float(df_h.imdb_rating.mean())

(6.8, 9.3, 8.130000000000003)

In [70]:
print("Min rating for Bollywood",float(df_b.imdb_rating.min()),"Max rating for Bollywood",float(df_b.imdb_rating.max()),"Mean rating for Bollywood",float(df_b.imdb_rating.mean()))

Min rating for Bollywood 1.9 Max rating for Bollywood 8.4 Mean rating for Bollywood 7.656250000000001


In [69]:
print("Min rating for Hollywood",float(df_h.imdb_rating.min()),"Max rating for Hollywood",float(df_h.imdb_rating.max()),"Mean rating for Hollywood",float(df_h.imdb_rating.mean()))

Min rating for Hollywood 6.8 Max rating for Hollywood 9.3 Mean rating for Hollywood 8.130000000000003
